apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: public1-manual
  namespace: apicast-jfxe3
spec:
  host: api.apps.edm3g8k3.eastus.aroapp.io
  path: /public1
  port:
    targetPort: proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicast-apicast
    weight: 100
  wildcardPolicy: None
